Resources:
  HIITVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value:  !Join ['', [!Ref "AWS::StackName", "-VPC" ]]
    
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: HIITVPC
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref HIITVPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref HIITVPC
      CidrBlock: 10.1.1.0/24
      AvailabilityZone: "eu-north-1a"       
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Public-A

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref HIITVPC
      CidrBlock: 10.1.2.0/24
      AvailabilityZone: "eu-north-1a"
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Private-A


  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref HIITVPC
      CidrBlock: 10.1.3.0/24
      AvailabilityZone: "eu-north-1b"
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Private-B