Resources:
  HIITVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/23
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value:  !Join ['', [!Ref "AWS::StackName", "-VPC" ]]
    
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: HIITVPC
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref HIITVPC
      InternetGatewayId: !Ref InternetGateway